-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 02, 2024 at 05:16 AM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `rpl`
--

-- --------------------------------------------------------

--
-- Table structure for table `resep`
--

CREATE TABLE `resep` (
  `id_resep` int(11) NOT NULL,
  `judul` varchar(255) NOT NULL,
  `bahan` text NOT NULL,
  `instruksi` text NOT NULL,
  `gambar` text DEFAULT 'assets/img/gambar.jpg'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `resep`
--

INSERT INTO `resep` (`id_resep`, `judul`, `bahan`, `instruksi`, `gambar`) VALUES
(1, 'Nasi Goreng', '<ul>\n  <li>5 sdm minyak goreng</li>\n  <li>150 gram daging ayam, potong dadu</li>\n  <li>3 buah bakso sapi, potong-potong</li>\n  <li>2 butir telur ayam, kocok lepas untuk orak-arik</li>\n  <li>500 gram nasi putih</li>\n  <li>1 batang daun bawang, potong serong</li>\n  <li>3 butir telur untuk telur mata sapi</li>\n  <li>5 butir bawang merah, haluskan</li>\n  <li>3 siung bawang putih, haluskan</li>\n  <li>2 butir kemiri, haluskan</li>\n  <li>3 buah cabai merah keriting, haluskan</li>\n  <li>2 sdm saus tomat</li>\n  <li>2 sdm kecap manis</li>\n  <li>1/2 sdt lada halus</li>\n  <li>1/2 penyedap rasa (opsional)</li>\n  <li>1 sdm bawang merah goreng</li>\n</ul>', '<ol>\r\n  <li>Panaskan 5 sdm minyak goreng dalam wajan atau penggorengan.</li>\r\n  <li>Tumis 5 butir bawang merah yang telah dihaluskan, 3 siung bawang putih yang telah dihaluskan, 2 butir kemiri yang telah dihaluskan, dan 3 buah cabai merah keriting yang telah dihaluskan hingga harum.</li>\r\n  <li>Setelah bumbu-bumbu harum, masukkan 150 gram daging ayam yang telah dipotong dadu, 3 buah bakso sapi yang telah dipotong-potong, dan 2 butir telur ayam yang telah dikocok lepas untuk orak-arik. Aduk rata dan tumis hingga daging ayam matang.</li>\r\n  <li>Setelah daging ayam matang, tambahkan 500 gram nasi putih ke dalam wajan. Aduk rata dengan bumbu dan bahan lainnya.</li>\r\n  <li>Tuangkan 2 sdm saus tomat dan 2 sdm kecap manis ke dalam wajan. Lanjutkan dengan menambahkan 1 batang daun bawang yang telah dipotong serong, 1/2 sdt lada halus, dan 1/2 penyedap rasa (jika digunakan). Aduk kembali hingga semua bahan tercampur rata dan nasi terasa panas.</li>\r\n  <li>Masak nasi goreng hingga semua bahan matang dan tercampur secara merata.</li>\r\n  <li>Setelah matang, angkat nasi goreng dari wajan dan tuangkan ke dalam piring saji.</li>\r\n  <li>Hidangkan nasi goreng hangat bersama dengan taburan 1 sdm bawang merah goreng dan telur mata sapi. Sajikan juga dengan acar campur dan emping goreng sebagai pelengkap.</li>\r\n</ol>', 'assets/img/nasi_goreng.jpg'),
(2, 'Nasi Kuning', '<ul>\r\n  <li>1½ kg beras, cuci dan tiriskan</li>\r\n  <li>1½ sendok makan kunyit parut</li>\r\n  <li>250 ml santan dari 1½ butir kelapa</li>\r\n  <li>3 batang serai, memarkan</li>\r\n  <li>6 lembar daun salam</li>\r\n  <li>8 lembar daun jeruk</li>\r\n  <li>1 sendok makan garam</li>\r\n  <li>2 sendok teh air jeruk nipis</li>\r\n</ul>', '<ul>\r\n  <li>Kukus 1½ kg beras sampai setengah matang (sekitar 15 menit) dan kemudian angkat.</li>\r\n  <li>Campurkan 1½ sendok makan kunyit parut dengan sedikit air, lalu saring dan buang ampasnya.</li>\r\n  <li>Campurkan air kunyit ke dalam 250 ml santan dari 1½ butir kelapa. Tambahkan juga 3 batang serai yang telah dimemarkan, 6 lembar daun salam, 8 lembar daun jeruk, dan 1 sendok makan garam. Masak sambil diaduk sekali-sekali sampai mendidih, lalu angkat.</li>\r\n  <li>Tambahkan 2 sendok teh air jeruk nipis ke dalam campuran santan tersebut, lalu aduk rata.</li>\r\n  <li>Masukkan beras yang telah dikukus ke dalam campuran santan, lalu aduk hingga merata.</li>\r\n  <li>Jerangkan campuran tersebut di atas api kecil sampai santan terserap oleh beras, kemudian angkat.</li>\r\n  <li>Kukus beras aron yang telah dimasak sebelumnya sampai matang (sekitar 45 menit), lalu angkat.</li>\r\n</ul>', 'assets/img/nasi_kuning.jpg'),
(3, 'Nasi Uduk', '<ul>\r\n  <li>400 gram beras</li>\r\n  <li>600 ml santan dari 1 butir kelapa</li>\r\n  <li>1 sendok teh garam</li>\r\n  <li>2 lembar daun salam</li>\r\n  <li>3 butir cengkeh</li>\r\n  <li>2 batang serai, ambil putihnya lalu dimemarkan</li>\r\n  <li>2 lembar daun pandan</li>\r\n  <li>3 butir telur, dikocok lepas lalu dibuat dadar dan diiris-iris</li>\r\n  <li>50 gram kerupuk kanji</li>\r\n  <li>300 gram tempe, dipotong panjang dan digoreng</li>\r\n  <li>4 siung bawang putih, diiris tipis</li>\r\n  <li>8 butir bawang merah, diiris tipis</li>\r\n  <li>4 buah cabai merah besar, dibuang biji lalu diiris serong</li>\r\n  <li>2 lembar daun salam</li>\r\n  <li>2 cm lengkuas, dimemarkan</li>\r\n  <li>2 sendok makan kecap manis</li>\r\n  <li>1 sendok teh air asam (dari 1 sendok teh asam jawa dan 1 sendok makan air)</li>\r\n  <li>2 sendok makan gula merah, disisir</li>\r\n  <li>1 sendok teh garam</li>\r\n  <li>2 sendok makan minyak untuk menumis</li>\r\n</ul>', '<ul>\r\n  <li>Masukkan 600 ml santan, 1 sendok teh garam, 2 lembar daun salam, 3 butir cengkeh, 2 batang serai yang dimemarkan, dan 2 lembar daun pandan ke dalam air. Didihkan campuran tersebut.</li>\r\n  <li>Tambahkan 400 gram beras ke dalam campuran santan yang sudah mendidih. Aduk hingga beras meresap.</li>\r\n  <li>Kukus beras yang telah dicampur dengan santan selama 30 menit atau sampai matang.</li>\r\n  <li>Tumis 4 siung bawang putih yang diiris tipis, 8 butir bawang merah yang diiris tipis, 4 buah cabai merah besar yang diiris serong, 2 lembar daun salam, dan 2 cm lengkuas yang dimemarkan sampai harum.</li>\r\n  <li>Tambahkan 2 sendok makan kecap manis, 1 sendok teh air asam (dari 1 sendok teh asam jawa dan 1 sendok makan air), 2 sendok makan gula merah yang disisir, dan 1 sendok teh garam ke dalam tumisan. Aduk rata.</li>\r\n  <li>Masukkan 300 gram tempe yang telah dipotong panjang dan digoreng ke dalam tumisan tersebut. Aduk hingga semua tercampur rata. Sisihkan.</li>\r\n  <li>Sajikan nasi uduk bersama dengan kering tempe, telur dadar yang diiris-iris, dan kerupuk kanji.</li>\r\n</ul>', 'assets/img/nasi_uduk.jpg'),
(4, 'Nasi Timbel', '<ul>\r\n  <li>100 gr nasi putih</li>\r\n  <li>1 potong daging ayam goreng</li>\r\n  <li>1 buah tahu kuning goreng</li>\r\n  <li>1 buah potongan tempe goreng</li>\r\n  <li>Daun pisang untuk membungkus secukupnya</li>\r\n  <li>3 buah irisan mentimun</li>\r\n  <li>2 tangkai daun kemangi (dicuci bersih)</li>\r\n  <li>1 lembar kol (dipotong menjadi 4 bagian)</li>\r\n  <li>Sambal goreng secukupnya</li>\r\n</ul>', '<ul>\r\n  <li>Cuci beras sampai bersih.</li>\r\n  <li>Didihkan air dalam panci, lalu masukkan beras dan aduk sampai air meresap.</li>\r\n  <li>Matikan api dan diamkan selama 10 menit.</li>\r\n  <li>Kukus beras selama 30 menit sampai matang. Angkat.</li>\r\n  <li>Ambil selembar daun pisang dan taruh 5 sendok makan nasi. Gulung daun pisang. Puntir ujung daun kanan dan kiri. Masukkan ke bagian tengah sambil didorong ke dalam.</li>\r\n  <li>Sajikan nasi timbel komplit dan dilengkapi dengan irisan mentimun, daun kemangi, kol, dan sambal.</li>\r\n</ul>', 'assets/img/nasi_timbel.jpg'),
(5, 'Kwetiau', '<ul>\r\n  <li>100 gram kwetiau basah</li>\r\n  <li>1 butir telur</li>\r\n  <li>Sawi hijau secukupnya</li>\r\n  <li>3 butir bakso</li>\r\n  <li>3 cabai keriting merah</li>\r\n  <li>1/2 sendok teh kaldu bubuk</li>\r\n  <li>1 sendok makan saus tiram</li>\r\n  <li>1/2 sendok teh kecap asin</li>\r\n  <li>Kecap secukupnya</li>\r\n  <li>3 siung bawang merah</li>\r\n  <li>1-2 siung bawang putih</li>\r\n  <li>1 butir kemiri</li>\r\n  <li>1 sendok teh garam</li>\r\n</ul>', '<ul>\r\n  <li>Panaskan sedikit minyak di wajan, lalu tumis 3 siung bawang merah, 1-2 siung bawang putih, dan 1 butir kemiri yang telah dihaluskan sampai harum.</li>\r\n  <li>Tambahkan 3 cabai keriting merah yang telah diiris tipis, tumis sebentar.</li>\r\n  <li>Masukkan 1 butir telur, aduk rata hingga menjadi orak-arik.</li>\r\n  <li>Masukkan 3 butir bakso yang telah diiris tipis dan sawi hijau secukupnya. Aduk hingga sawi sedikit layu.</li>\r\n  <li>Tambahkan 100 gram kwetiau basah, aduk rata.</li>\r\n  <li>Tuangkan 1 sendok makan saus tiram, 1/2 sendok teh kecap asin, dan kecap secukupnya. Aduk rata hingga semua bahan tercampur.</li>\r\n  <li>Bumbui dengan 1/2 sendok teh kaldu bubuk dan 1 sendok teh garam. Aduk rata dan masak hingga semua bahan matang dan bumbu meresap.</li>\r\n  <li>Angkat dan sajikan kwetiau goreng hangat.</li>\r\n</ul>', 'assets/img/kwetiau.jpg'),
(6, 'Bubur Ayam', '<ul>\r\n  <li>300 gram beras</li>\r\n  <li>2 liter air</li>\r\n  <li>2 lembar daun salam</li>\r\n  <li>Garam secukupnya</li>\r\n  <li>2 sdm santan instan</li>\r\n  <li>300 gram dada ayam</li>\r\n  <li>1 liter air</li>\r\n  <li>3 siung bawang putih</li>\r\n  <li>3 butir kemiri</li>\r\n  <li>2 ruas jari kunyit</li>\r\n  <li>½ sdt lada bubuk</li>\r\n  <li>Garam, gula merah, dan kaldu bubuk secukupnya</li>\r\n  <li>3 lembar daun salam</li>\r\n  <li>4 lembar daun jeruk</li>\r\n  <li>1 batang serai, memarkan</li>\r\n  <li>65 ml santan instan</li>\r\n  <li>Kedelai goreng dan kerupuk untuk taburan</li>\r\n  <li>Irisan daun bawang untuk taburan</li>\r\n  <li>Bawang merah goreng untuk taburan</li>\r\n  <li>Sambal rawit goreng sebagai pelengkap</li>\r\n</ul>', '<ul>\r\n  <li>Masak 300 gram beras dengan 2 liter air dan 2 lembar daun salam hingga beras menjadi bubur. Tambahkan garam secukupnya dan 2 sdm santan instan. Aduk rata dan masak hingga bubur matang.</li>\r\n  <li>Rebus 300 gram dada ayam dalam 1 liter air hingga matang. Angkat dan suwir-suwir ayam, sisihkan kaldu ayamnya.</li>\r\n  <li>Haluskan 3 siung bawang putih, 3 butir kemiri, 2 ruas jari kunyit, dan ½ sdt lada bubuk.</li>\r\n  <li>Tumis bumbu yang dihaluskan hingga harum, tambahkan garam, gula merah, dan kaldu bubuk secukupnya.</li>\r\n  <li>Masukkan 3 lembar daun salam, 4 lembar daun jeruk, dan 1 batang serai yang telah dimemarkan. Aduk rata.</li>\r\n  <li>Tuangkan 65 ml santan instan ke dalam tumisan bumbu dan aduk rata.</li>\r\n  <li>Masukkan suwiran ayam ke dalam tumisan bumbu, aduk rata, dan masak hingga bumbu meresap. Angkat dan sisihkan.</li>\r\n  <li>Sajikan bubur dalam mangkuk, tambahkan suwiran ayam berbumbu di atasnya.</li>\r\n  <li>Taburi dengan kedelai goreng, kerupuk, irisan daun bawang, dan bawang merah goreng.</li>\r\n  <li>Hidangkan dengan sambal rawit goreng sebagai pelengkap.</li>\r\n</ul>', 'assets/img/bubur_ayam.jpeg'),
(7, 'Bubur Kacang Hijau', '<ul>\r\n  <li>100 gram kacang hijau</li>\r\n  <li>65 ml santan instan</li>\r\n  <li>Selembar daun pandan</li>\r\n  <li>Gula pasir sesuai selera</li>\r\n  <li>Sedikit garam</li>\r\n  <li>Jahe sesuai selera</li>\r\n  <li>650 ml air</li>\r\n</ul>', '<ul>\r\n  <li>Cuci bersih 100 gram kacang hijau, lalu rendam dalam air selama beberapa jam atau semalaman agar cepat empuk saat dimasak.</li>\r\n  <li>Rebus 650 ml air dalam panci, masukkan kacang hijau yang telah direndam dan masak hingga kacang hijau empuk.</li>\r\n  <li>Tambahkan selembar daun pandan yang telah disimpul dan jahe sesuai selera yang telah digeprek ke dalam rebusan kacang hijau. Masak hingga harum.</li>\r\n  <li>Masukkan gula pasir sesuai selera dan sedikit garam, aduk hingga gula larut dan merata.</li>\r\n  <li>Tuangkan 65 ml santan instan, aduk rata dan masak hingga mendidih. Pastikan santan tidak pecah dengan terus mengaduk perlahan.</li>\r\n  <li>Angkat bubur kacang hijau dari kompor dan sajikan hangat atau dingin sesuai selera.</li>\r\n</ul>', 'assets/img/burjo.jpeg'),
(8, 'Bubur Ketan Hitam', '<ul>\r\n  <li>1 kg beras ketan hitam yang sudah disosoh</li>\r\n  <li>Air secukupnya</li>\r\n  <li>2 lembar daun pandan, potong-potong</li>\r\n  <li>1 sdt garam</li>\r\n  <li>250 g gula pasir</li>\r\n  <li>Saus Santan:</li>\r\n  <ul>\r\n    <li>750 ml santan kelapa sedang</li>\r\n    <li>1 lembar daun pandan, ikat</li>\r\n    <li>1/2 sdt garam</li>\r\n  </ul>\r\n</ul>', '<ul>\r\n  <li>Cuci bersih 1 kg beras ketan hitam yang sudah disosoh, lalu rendam dalam air selama beberapa jam atau semalaman agar cepat empuk saat dimasak.</li>\r\n  <li>Rebus beras ketan hitam dengan air secukupnya hingga mendidih. Tambahkan 2 lembar daun pandan yang telah dipotong-potong dan 1 sdt garam. Masak hingga beras ketan hitam empuk dan airnya menyusut.</li>\r\n  <li>Setelah ketan hitam empuk, tambahkan 250 g gula pasir dan aduk rata. Masak hingga gula larut dan tercampur rata dengan bubur ketan hitam. Angkat dan sisihkan.</li>\r\n  <li>Untuk membuat saus santan, rebus 750 ml santan kelapa sedang dengan 1 lembar daun pandan yang telah diikat dan 1/2 sdt garam. Masak dengan api kecil sambil terus diaduk agar santan tidak pecah. Angkat setelah mendidih.</li>\r\n  <li>Sajikan bubur ketan hitam dalam mangkuk, lalu tuangkan saus santan di atasnya. Hidangkan hangat atau dingin sesuai selera.</li>\r\n</ul>', 'assets/img/burtem.jpeg'),
(9, 'Bubur Sumsum', '<ul>\r\n  <li>100 g tepung beras</li>\r\n  <li>2 sdm gula pasir</li>\r\n  <li>1 sdt garam</li>\r\n  <li>1 sdt vanili bubuk</li>\r\n  <li>400 ml santan cair</li>\r\n  <li>200 g gula jawa</li>\r\n  <li>1 sdt garam</li>\r\n  <li>400 ml air</li>\r\n</ul>', '<ul>\r\n  <li>Campurkan 100 g tepung beras, 2 sdm gula pasir, 1 sdt garam, dan 1 sdt vanili bubuk dalam sebuah mangkuk. Aduk rata.</li>\r\n  <li>Tuang 400 ml santan cair secara bertahap ke dalam campuran tepung beras sambil diaduk hingga adonan halus dan tidak ada yang menggumpal.</li>\r\n  <li>Masak adonan tepung beras dan santan di atas api kecil sambil terus diaduk hingga mengental dan matang. Angkat dan sisihkan.</li>\r\n  <li>Untuk membuat saus gula jawa, rebus 200 g gula jawa dengan 400 ml air hingga gula larut dan mendidih. Tambahkan 1 sdt garam dan aduk rata. Masak hingga saus gula jawa sedikit mengental. Angkat dan saring untuk menghilangkan kotoran jika perlu.</li>\r\n  <li>Sajikan bubur sumsum dalam mangkuk, lalu tuangkan saus gula jawa di atasnya.</li>\r\n</ul>', 'assets/img/bursum.jpeg'),
(10, 'Seblak', '<ul>\r\n  <li>1 sachet makaroni kering (apa saja)</li>\r\n  <li>Kerupuk bawang, direndam air panas</li>\r\n  <li>Ceker ayam, direbus</li>\r\n  <li>1 buah telur ayam</li>\r\n  <li>6 buah cabai rawit merah</li>\r\n  <li>3 buah cabai rawit hijau</li>\r\n  <li>1/2 pcs mie instan Korea (tanpa bumbu)</li>\r\n  <li>1/2 sdm lada bubuk</li>\r\n  <li>1 sachet bawang goreng instan tabur</li>\r\n  <li>6 siung bawang putih</li>\r\n  <li>1 sachet kecil tomat</li>\r\n  <li>4 sachet kecil saus cabai</li>\r\n  <li>Penyedap rasa secukupnya</li>\r\n  <li>Garam secukupnya</li>\r\n  <li>Gula secukupnya</li>\r\n</ul>', '<ul>\r\n  <li>Rebus 1 sachet makaroni kering hingga al dente, tiriskan.</li>\r\n  <li>Rendam kerupuk bawang dalam air panas hingga lembut, tiriskan.</li>\r\n  <li>Rebus ceker ayam hingga empuk, sisihkan.</li>\r\n  <li>Rebus 1/2 pcs mie instan Korea tanpa menggunakan bumbu, tiriskan.</li>\r\n  <li>Haluskan 6 siung bawang putih, 6 buah cabai rawit merah, dan 3 buah cabai rawit hijau.</li>\r\n  <li>Panaskan sedikit minyak di wajan, tumis bumbu halus hingga harum.</li>\r\n  <li>Masukkan ceker ayam rebus dan aduk rata dengan bumbu.</li>\r\n  <li>Tambahkan makaroni, mie instan, dan kerupuk bawang yang telah direndam. Aduk rata.</li>\r\n  <li>Pecahkan 1 buah telur ayam, aduk cepat hingga tercampur rata.</li>\r\n  <li>Tambahkan 1/2 sdm lada bubuk, 1 sachet kecil tomat, dan 4 sachet kecil saus cabai. Aduk hingga merata.</li>\r\n  <li>Tambahkan penyedap rasa, garam, dan gula secukupnya. Aduk rata dan masak hingga semua bahan matang.</li>\r\n  <li>Sajikan hidangan dalam piring dan taburi dengan 1 sachet bawang goreng instan.</li>\r\n</ul>', 'assets/img/seblak.jpeg'),
(11, 'Ayam Bakar Bumbu Kuning', '<ul>\r\n  <li>1 ekor ayam pejantan, potong 4 bagian</li>\r\n  <li>500 ml air</li>\r\n  <li>1 sdt garam</li>\r\n  <li>2 sdt kaldu ayam</li>\r\n  <li>2 batang serai</li>\r\n  <li>1 sdt gula pasir</li>\r\n  <li>6 bawang merah</li>\r\n  <li>5 bawang putih</li>\r\n  <li>6 butir kemiri</li>\r\n  <li>4 cm kunyit</li>\r\n  <li>1 sdt ketumbar</li>\r\n  <li>1 cm jahe</li>\r\n  <li>2 cm lengkuas</li>\r\n</ul>', '<ul>\r\n  <li>Pertama-tama, rebus 500 ml air dalam panci.</li>\r\n  <li>Masukkan potongan ayam ke dalam panci yang berisi air rebusan.</li>\r\n  <li>Tambahkan 1 sdt garam, 2 sdt kaldu ayam, 2 batang serai, dan 1 sdt gula pasir ke dalam panci.</li>\r\n  <li>Masak ayam hingga empuk dan bumbu meresap, kemudian angkat ayam dan sisihkan.</li>\r\n  <li>Haluskan 6 bawang merah, 5 bawang putih, 6 butir kemiri, 4 cm kunyit, 1 sdt ketumbar, 1 cm jahe, dan 2 cm lengkuas.</li>\r\n  <li>Tumis bumbu halus hingga harum dan matang.</li>\r\n  <li>Setelah itu, bakar ayam sambil dioles dengan bumbu kuning yang sudah ditumis hingga matang dan berwarna kecokelatan.</li>\r\n  <li>Angkat dan sajikan ayam bakar bumbu kuning bersama nasi hangat atau lalapan.</li>\r\n</ul>', 'assets/img/bakar_kuning.jpeg'),
(12, 'Ayam Goreng', '<ul>\r\n  <li>1 ekor ayam, potong menjadi bagian-bagian sesuai selera</li>\r\n  <li>2 sdt garam</li>\r\n  <li>1 sdt lada bubuk</li>\r\n  <li>2 siung bawang putih, haluskan</li>\r\n  <li>1 cm jahe, parut</li>\r\n  <li>2 lembar daun salam</li>\r\n  <li>Minyak goreng secukupnya untuk menggoreng</li>\r\n</ul>', '<ul>\r\n  <li>Cuci bersih potongan ayam, kemudian lumuri dengan garam, lada bubuk, bawang putih, dan jahe. Diamkan selama minimal 30 menit agar bumbu meresap.</li>\r\n  <li>Panaskan minyak goreng dalam wajan dengan api sedang.</li>\r\n  <li>Setelah minyak panas, goreng potongan ayam secara bertahap hingga matang dan kecokelatan. Pastikan ayam matang sempurna di bagian dalam.</li>\r\n  <li>Angkat ayam dan tiriskan dari minyak berlebih menggunakan tisu dapur atau rak tirisan.</li>\r\n  <li>Sajikan ayam goreng hangat bersama nasi dan sambal favorit.</li>\r\n</ul>', 'assets/img/ayam_goreng.jpeg'),
(13, 'Ayam Bakar', '<ul>\r\n  <li>700 gr ayam, potong sesuai selera</li>\r\n  <li>5-6 sdm kecap manis</li>\r\n  <li>1 sdm mentega</li>\r\n  <li>1 sdm gula merah, sisir</li>\r\n  <li>1 sdm air asam Jawa</li>\r\n  <li>Air putih atau air kelapa secukupnya</li>\r\n  <li>Garam, merica, dan kaldu jamur secukupnya</li>\r\n  <li>2 lembar daun salam</li>\r\n  <li>1 batang serai, geprek</li>\r\n  <li>1 ruas lengkuas, geprek</li>\r\n  <li>4 lembar daun jeruk, sobek-sobek</li>\r\n</ul>', '<ul>\n  <li>Panaskan mentega dalam wajan dengan api sedang.</li>\n  <li>Tumis bumbu-bumbu aromatik seperti daun salam, serai, lengkuas, dan daun jeruk hingga harum.</li>\n  <li>Masukkan potongan ayam, aduk rata dengan bumbu, dan biarkan ayam sedikit berubah warna.</li>\n  <li>Tambahkan kecap manis, gula merah, dan air asam Jawa. Aduk rata.</li>\n  <li>Tuang air secukupnya hingga ayam terendam. Masak dengan api kecil hingga ayam matang dan bumbu meresap. Sesekali aduk agar tidak gosong dan cek kecukupan rasa.</li>\n  <li>Setelah ayam matang dan bumbu meresap, angkat dan sajikan.</li>\n</ul>', 'assets/img/ayam_bakar.jpeg'),
(14, 'Ayam Serundeng', '<ul>\r\n  <li>500 gram paha ayam</li>\r\n  <li>4 siung bawang putih</li>\r\n  <li>6 siung bawang merah</li>\r\n  <li>4 cm jahe</li>\r\n  <li>3 cm kunyit</li>\r\n  <li>2 batang serai, memarkan</li>\r\n  <li>2 lembar daun salam</li>\r\n  <li>1/2 butir kelapa parut</li>\r\n  <li>2 sdm lengkuas parut</li>\r\n  <li>1 sdm garam</li>\r\n  <li>200 ml air</li>\r\n  <li>Kaldu bubuk</li>\r\n</ul>', '<ul>\r\n  <li>Cuci bersih paha ayam, potong-potong sesuai selera, kemudian sisihkan.</li>\r\n  <li>Haluskan bawang putih, bawang merah, jahe, dan kunyit. Tumis bumbu yang telah dihaluskan dengan sedikit minyak hingga harum.</li>\r\n  <li>Masukkan potongan ayam ke dalam tumisan bumbu, aduk rata hingga ayam terbalut dengan bumbu.</li>\r\n  <li>Tambahkan batang serai yang telah dimemarkan, daun salam, kelapa parut, dan lengkuas parut. Lanjutkan mengaduk hingga semua bahan tercampur rata.</li>\r\n  <li>Tuang air, tambahkan garam, dan sedikit kaldu bubuk untuk memberi rasa. Aduk kembali dan biarkan ayam mendidih hingga empuk dan bumbu meresap.</li>\r\n  <li>Setelah ayam matang dan bumbu meresap, angkat dan tiriskan.</li>\r\n  <li>Ayam goreng kunyit siap disajikan. Nikmati dengan nasi hangat dan sambal favorit.</li>\r\n</ul>', 'assets/img/ayam_serundeng.jpeg'),
(15, 'Steak Ayam', '<ul>\r\n  <li>300 gram fillet ayam</li>\r\n  <li>3 siung bawang putih</li>\r\n  <li>2 butir telur</li>\r\n  <li>2 sdm tepung tapioka</li>\r\n  <li>1/2 sdt lada bubuk</li>\r\n  <li>1/2 sdt garam</li>\r\n  <li>1 sdt kaldu jamur</li>\r\n  <li>2 siung bawang putih, geprek cincang halus</li>\r\n  <li>1/2 buah bawang bombai, cincang halus</li>\r\n  <li>1 sachet saus lada hitam</li>\r\n  <li>1/2 sdm saus tiram</li>\r\n  <li>1/2 sdm saus tomat</li>\r\n  <li>1/2 sdm kecap asin</li>\r\n  <li>1/2 sdt kaldu jamur</li>\r\n  <li>1/4 sdt lada bubuk</li>\r\n  <li>1/2 sdt maizena, larutkan dengan sedikit air</li>\r\n  <li>200 ml air</li>\r\n</ul>', '<ul>\r\n  <li>Cincang halus 3 siung bawang putih.</li>\r\n  <li>Potong fillet ayam sesuai selera.</li>\r\n  <li>Kocok 2 butir telur dalam sebuah mangkuk.</li>\r\n  <li>Di mangkuk lain, campurkan fillet ayam dengan tepung tapioka, lada bubuk, garam, dan 1 sdt kaldu jamur. Pastikan fillet ayam terbalut rata dengan bumbu.</li>\r\n  <li>Goreng fillet ayam hingga kecokelatan dan matang. Angkat dan tiriskan.</li>\r\n  <li>Tumis bawang putih cincang dan bawang bombai hingga harum.</li>\r\n  <li>Masukkan saus lada hitam, saus tiram, saus tomat, kecap asin, sisa kaldu jamur, dan lada bubuk. Aduk rata.</li>\r\n  <li>Tuangkan air ke dalam tumisan bumbu. Biarkan mendidih.</li>\r\n  <li>Masukkan larutan maizena ke dalam tumisan bumbu, aduk rata hingga saus mengental.</li>\r\n  <li>Masukkan fillet ayam goreng ke dalam saus lada hitam yang telah mengental. Aduk rata hingga ayam terbalut dengan saus.</li>\r\n  <li>Angkat dan sajikan ayam saus lada hitam panas dengan nasi hangat.</li>\r\n</ul>', 'assets/img/steak_ayam.jpeg'),
(16, 'Rendang', '<ul>\n  <li>500 gr daging</li>\n  <li>1 batang serai, geprek</li>\n  <li>3 lembar daun jeruk</li>\n  <li>2 lembar daun salam</li>\n  <li>1 ruas lengkuas, geprek</li>\n  <li>2 cm kayu manis</li>\n  <li>1 sdt gula merah</li>\n  <li>1 sdt kaldu sapi</li>\n  <li>1/2 sdt garam</li>\n  <li>1/2 sdt jintan bubuk</li>\n  <li>1/2 sdt merica bubuk</li>\n  <li>Jeruk nipis</li>\n  <li>500 ml santan dari 1/2 kelapa</li>\n</ul>\nBumbu halus:\n\n<ul>\n  <li>4 siung bawang putih</li>\n  <li>6 butir bawang merah</li>\n  <li>2 butir kemiri</li>\n  <li>1/2 sdt ketumbar</li>\n  <li>3 cabai merah besar (buang bijinya)</li>\n  <li>2 cm kunyit</li>\n  <li>3 cm jahe</li>\n</ul>', '<ul>\r\n  <li>Potong daging sesuai selera.</li>\r\n  <li>Panaskan sedikit minyak dalam wajan atau panci.</li>\r\n  <li>Tumis bumbu-bumbu aromatik seperti serai, daun jeruk, daun salam, lengkuas, dan kayu manis hingga harum.</li>\r\n  <li>Masukkan potongan daging ke dalam wajan atau panci. Aduk rata dan tumis hingga daging berubah warna.</li>\r\n  <li>Tambahkan gula merah, kaldu sapi, garam, jintan bubuk, dan merica bubuk. Aduk rata hingga bumbu meresap ke daging.</li>\r\n  <li>Tuang santan ke dalam wajan atau panci. Aduk rata.</li>\r\n  <li>Biarkan rendang mendidih dengan api kecil hingga santan menyusut dan bumbu meresap ke daging. Pastikan untuk sesekali diaduk agar tidak gosong.</li>\r\n  <li>Tambahkan perasan jeruk nipis sesuai selera.</li>\r\n  <li>Biarkan daging rendang matang dan berkuah kental.</li>\r\n  <li>Angkat daging rendang dan sajikan dengan nasi hangat.</li>\r\n</ul>', 'assets/img/rendang.jpeg'),
(17, 'Pecel Lele', '<ul>\r\n  <li>1 kg ikan lele, beri air perasan jeruk nipis</li>\r\n  <li>3 siung bawang putih</li>\r\n  <li>3 cm jahe</li>\r\n  <li>1 telunjuk kunyit</li>\r\n  <li>1 sdm garam</li>\r\n  <li>1 sdm ketumbar</li>\r\n  <li>Minyak goreng</li>\r\n  <li>Aneka sayuran (timun, tomat, dan selada)</li>\r\n</ul>\r\nBahan untuk sambal:\r\n\r\n<ul>\r\n  <li>10 buah cabai rawit merah (tergantung selera)</li>\r\n  <li>2 buah tomat</li>\r\n  <li>6 butir bawang merah</li>\r\n  <li>2 siung bawang putih</li>\r\n  <li>1 sdt terasi matang</li>\r\n  <li>1 sdm kacang tanah sangrai</li>\r\n  <li>Gula merah secukupnya</li>\r\n  <li>1 sdt garam</li>\r\n  <li>1/2 sdt kaldu jamur</li>\r\n  <li>Daun kemangi</li>\r\n  <li>Jeruk limau, peras airnya</li>\r\n</ul>', '<ul>\r\n  <li>Haluskan bawang putih, jahe, kunyit, garam, dan ketumbar. Campurkan dengan ikan lele dan diamkan selama beberapa saat.</li>\r\n  <li>Goreng ikan lele hingga matang dan kecokelatan. Angkat dan tiriskan.</li>\r\n  <li>Persiapkan sayuran sebagai pelengkap.</li>\r\n  <li>Untuk membuat sambal, haluskan cabai rawit merah, tomat, bawang merah, bawang putih, terasi matang, dan kacang tanah sangrai.</li>\r\n  <li>Tumis bumbu halus hingga harum. Tambahkan gula merah, garam, dan kaldu jamur. Aduk rata.</li>\r\n  <li>Tambahkan daun kemangi dan perasan air jeruk limau. Aduk kembali sebentar.</li>\r\n  <li>Sambal siap disajikan bersama dengan ikan lele goreng dan aneka sayuran.</li>\r\n</ul>', 'assets/img/pecel_lele.jpeg'),
(18, 'Mie Ayam', '<ul>\r\n  <li>500 g fillet dada ayam</li>\r\n  <li>8 siung bawang merah</li>\r\n  <li>5 siung bawang putih</li>\r\n  <li>1 ruas kunyit</li>\r\n  <li>6 butir kemiri, sangrai</li>\r\n  <li>3 lembar daun salam</li>\r\n  <li>4 lembar daun jeruk</li>\r\n  <li>2 batang serai</li>\r\n  <li>1 ruas jahe</li>\r\n  <li>1 ruas lengkuas</li>\r\n  <li>500 ml air</li>\r\n  <li>150 ml minyak goreng</li>\r\n  <li>2 batang daun bawang</li>\r\n  <li>1 sdm gula pasir</li>\r\n  <li>1/2 sdt lada bubuk</li>\r\n  <li>1 sdt kaldu bubuk</li>\r\n  <li>1 sdt garam</li>\r\n  <li>60 ml kecap manis</li>\r\n  <li>200 ml minyak goreng</li>\r\n  <li>200 g kulit ayam</li>\r\n</ul>\r\nBahan-bahan untuk kuah mie ayam:\r\n\r\n<ul>\r\n  <li>3 siung bawang putih</li>\r\n  <li>5 siung bawang merah</li>\r\n  <li>1 sdt ketumbar</li>\r\n  <li>1 batang serai</li>\r\n  <li>1 ruas jahe</li>\r\n  <li>350 ml air</li>\r\n  <li>3 sdm garam</li>\r\n  <li>1/2 sdt kaldu bubuk</li>\r\n  <li>2 sdm kecap manis</li>\r\n  <li>1 L air</li>\r\n</ul>', '<ul>\r\n  <li>Haluskan bawang merah, bawang putih, kunyit, dan kemiri yang telah disangrai.</li>\r\n  <li>Tumis bumbu halus bersama dengan daun salam, daun jeruk, serai, jahe, dan lengkuas hingga harum.</li>\r\n  <li>Masukkan fillet dada ayam yang telah dipotong ke dalam tumisan bumbu. Tumis hingga ayam berubah warna.</li>\r\n  <li>Tambahkan air, gula pasir, lada bubuk, kaldu bubuk, garam, dan kecap manis. Aduk rata dan biarkan hingga ayam matang dan bumbu meresap.</li>\r\n  <li>Sementara itu, goreng kulit ayam hingga krispi. Angkat dan tiriskan.</li>\r\n  <li>Goreng mie ayam dalam minyak panas hingga matang dan kecokelatan. Angkat dan tiriskan.</li>\r\n  <li>Siapkan kuah mie ayam dengan menumis bawang putih, bawang merah, ketumbar, serai, jahe, dan air hingga mendidih. Tambahkan garam, kaldu bubuk, dan kecap manis. Aduk rata.</li>\r\n  <li>Rangkai mie ayam, kulit ayam krispi, dan daun bawang dalam mangkuk. Siram dengan kuah panas.</li>\r\n</ul>', 'assets/img/mie_ayam.jpeg'),
(19, 'Chicken Parmesan ', '<ul>\r\n  <li>4 potong dada ayam, dipukul tipis</li>\r\n  <li>1 cangkir tepung terigu</li>\r\n  <li>2 butir telur, dikocok lepas</li>\r\n  <li>2 cangkir tepung roti</li>\r\n  <li>1/2 cangkir keju parmesan, parut</li>\r\n  <li>2 cangkir saus marinara</li>\r\n  <li>1 cangkir mozzarella, parut</li>\r\n  <li>Garam dan merica secukupnya</li>\r\n  <li>Minyak sayur untuk menggoreng</li>\r\n  <li>Daun basil segar untuk hiasan</li>\r\n</ul>', '<ul>\r\n  <li>Panaskan minyak dalam wajan besar.</li>\r\n  <li>Siapkan tiga mangkuk terpisah. Isi satu dengan tepung terigu, satu dengan telur yang telah dikocok, dan satu lagi dengan campuran tepung roti, keju parmesan, garam, dan merica.</li>\r\n  <li>Gulingkan potongan dada ayam dalam tepung terigu, lalu celupkan ke dalam telur, dan terakhir gulingkan dalam campuran tepung roti.</li>\r\n  <li>Goreng potongan ayam dalam minyak panas hingga kecokelatan dan matang sempurna.</li>\r\n  <li>Preheat oven. Letakkan potongan ayam yang sudah digoreng di atas loyang yang dilapisi kertas roti.</li>\r\n  <li>Siram saus marinara di atas setiap potongan ayam, lalu taburkan mozzarella parut di atasnya.</li>\r\n  <li>Panggang di oven yang sudah dipanaskan hingga keju meleleh dan mulai kecokelatan, sekitar 15-20 menit.</li>\r\n  <li>Angkat, hiasi dengan daun basil segar, dan sajikan.</li>\r\n</ul>', 'assets/img/chick_parm.jpeg'),
(20, 'Chicken Alfredo ', '<ul>\r\n  <li>300 gram spaghetti</li>\r\n  <li>300 gram dada ayam, potong dadu kecil</li>\r\n  <li>3 siung bawang putih, cincang halus</li>\r\n  <li>1/2 cup mentega</li>\r\n  <li>1 cup krim kental</li>\r\n  <li>1 cup parmesan, parut</li>\r\n  <li>1/2 cup parsley, cincang halus</li>\r\n  <li>Garam dan merica secukupnya</li>\r\n  <li>Minyak zaitun</li>\r\n</ul>', '<ul>\r\n  <li>Masak spaghetti sesuai petunjuk pada kemasan. Tiriskan dan sisihkan.</li>\r\n  <li>Panaskan minyak zaitun dalam wajan besar. Tumis bawang putih hingga harum.</li>\r\n  <li>Masukkan potongan ayam, garam, dan merica. Masak hingga ayam matang sempurna.</li>\r\n  <li>Tambahkan mentega dan krim kental. Aduk rata dan biarkan mendidih.</li>\r\n  <li>Tambahkan parmesan parut dan parsley cincang. Aduk rata hingga keju meleleh dan saus mengental.</li>\r\n  <li>Tuangkan saus di atas spaghetti yang telah dimasak. Aduk rata hingga semua spaghetti terbalut dengan saus.</li>\r\n  <li>Sajikan segera dan taburi dengan sedikit parsley cincang sebagai hiasan.</li>\r\n</ul>', 'assets/img/chick_alfredo.jpeg'),
(21, 'Chicken Fajitas', '<ul>\n  <li>300 gram dada ayam, potong tipis</li>\n  <li>1 buah paprika merah, iris tipis</li>\n  <li>1 buah paprika hijau, iris tipis</li>\n  <li>1 buah bawang bombay, iris tipis</li>\n  <li>2 sendok makan minyak zaitun</li>\n  <li>1 sendok makan bubuk cabai</li>\n  <li>1 sendok makan bubuk jintan</li>\n  <li>Garam dan merica secukupnya</li>\n  <li>Tortilla, untuk penyajian</li>\n  <li>Parsley segar, cincang halus, untuk hiasan</li>\n</ul>', '<ul>\r\n  <li>Panaskan minyak zaitun dalam wajan. Tumis bawang bombay hingga harum.</li>\r\n  <li>Tambahkan potongan ayam dan masak hingga ayam berubah warna.</li>\r\n  <li>Masukkan paprika merah dan hijau. Tambahkan bubuk cabai, bubuk jintan, garam, dan merica. Aduk rata dan masak hingga sayuran layu.</li>\r\n  <li>Sajikan ayam fajitas bersama dengan tortilla. Taburi dengan parsley cincang sebagai hiasan.</li>\r\n</ul>', 'assets/img/chick_fajitas.jpeg'),
(22, 'Spaghetti Aglio e Olio', '<ul>\r\n  <li>300 gram spaghetti</li>\r\n  <li>4 siung bawang putih, cincang halus</li>\r\n  <li>1/2 cup minyak zaitun extra virgin</li>\r\n  <li>1 sendok makan cabai merah kering, cincang halus</li>\r\n  <li>Peterseli segar, cincang halus, untuk hiasan</li>\r\n  <li>Garam secukupnya</li>\r\n</ul>', '<ul>\r\n  <li>Masak spaghetti sesuai petunjuk pada kemasan. Tiriskan dan sisihkan.</li>\r\n  <li>Panaskan minyak zaitun dalam wajan. Tumis bawang putih dan cabai merah kering hingga harum.</li>\r\n  <li>Tambahkan spaghetti yang telah dimasak ke dalam tumisan bawang putih dan cabai merah kering. Aduk rata hingga spaghetti terbalut dengan minyak dan bumbu.</li>\r\n  <li>Sajikan spaghetti dalam piring saji dan taburi dengan peterseli cincang sebagai hiasan.</li>\r\n</ul>', 'assets/img/spagheti_olio.jpeg'),
(23, 'Beef Burger', '<ul>\r\n  <li>300 gram daging sapi giling</li>\r\n  <li>4 roti burger</li>\r\n  <li>4 lembar keju cheddar</li>\r\n  <li>4 lembar selada</li>\r\n  <li>1 buah tomat, iris tipis</li>\r\n  <li>1 buah bawang bombay, iris tipis</li>\r\n  <li>4 sendok makan saus tomat</li>\r\n  <li>Garam dan merica secukupnya</li>\r\n  <li>Minyak zaitun</li>\r\n</ul>', '<ul>\r\n  <li>Bentuk daging sapi giling menjadi bulatan tipis sesuai ukuran roti burger. Bumbui dengan garam dan merica.</li>\r\n  <li>Panaskan minyak zaitun dalam wajan. Panggang daging sapi giling hingga matang dan kecokelatan di kedua sisinya.</li>\r\n  <li>Panggang roti burger dalam oven atau di atas wajan hingga sedikit krispi.</li>\r\n  <li>Susun roti burger dengan daging panggang, keju cheddar, selada, tomat, dan bawang bombay. Tambahkan saus tomat.</li>\r\n  <li>Sajikan burger panas dengan kentang goreng atau keripik sebagai pelengkap.</li>\r\n</ul>', 'assets/img/burger.jpeg'),
(24, 'Sate Ayam', '<ul>\n  <li>300 gram daging ayam, potong dadu</li>\n  <li>1 buah bawang merah, haluskan</li>\n  <li>2 siung bawang putih, haluskan</li>\n  <li>1 sendok makan kecap manis</li>\n  <li>1 sendok makan minyak goreng</li>\n  <li>Garam dan merica secukupnya</li>\n  <li>Tusuk sate, rendam dalam air</li>\n</ul>', '<ul>\n  <li>Campur daging ayam dengan bawang merah, bawang putih, kecap manis, minyak goreng, garam, dan merica dalam sebuah mangkuk. Aduk rata dan diamkan selama minimal 30 menit untuk marinasi.</li>\n  <li>Tusukkan potongan daging ayam yang telah dimarinasi ke dalam tusuk sate.</li>\n  <li>Panaskan grill atau panggangan. Panggang sate ayam di atasnya hingga matang dan berwarna kecokelatan, sambil sesekali diolesi sisa marinasi.</li>\n  <li>Angkat sate ayam dari panggangan dan sajikan dengan bumbu kacang dan lontong atau nasi putih.</li>\n</ul>', 'assets/img/sate_ayam.jpeg'),
(25, 'Mac n Cheese', '<ul>\r\n  <li>300 gram pasta macaroni</li>\r\n  <li>3 sendok makan mentega</li>\r\n  <li>3 sendok makan tepung terigu</li>\r\n  <li>500 ml susu cair</li>\r\n  <li>200 gram keju cheddar parut</li>\r\n  <li>100 gram keju mozarella parut</li>\r\n  <li>Garam dan merica secukupnya</li>\r\n  <li>Optional: breadcrumbs sebagai topping</li>\r\n</ul>', '<ul>\r\n  <li>Rebus pasta macaroni sesuai petunjuk pada kemasan. Tiriskan dan sisihkan.</li>\r\n  <li>Siapkan panci lain, lelehkan mentega di dalamnya. Tambahkan tepung terigu, aduk hingga tercampur rata dan membentuk pasta.</li>\r\n  <li>Tuang susu cair sedikit demi sedikit sambil terus diaduk hingga kental dan tanpa gumpalan.</li>\r\n  <li>Tambahkan keju cheddar parut dan keju mozarella parut ke dalam campuran susu. Aduk rata hingga keju meleleh dan saus menjadi kental.</li>\r\n  <li>Bumbui saus dengan garam dan merica sesuai selera.</li>\r\n  <li>Masukkan pasta macaroni yang telah direbus ke dalam saus keju. Aduk rata hingga semua pasta terbalut dengan saus keju.</li>\r\n  <li>Sajikan Mac and Cheese hangat. Jika diinginkan, taburi dengan breadcrumbs sebagai topping sebelum disajikan.</li>\r\n</ul>', 'assets/img/macncheese.jpeg');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `nama` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `nama`, `username`, `password`) VALUES
(6, 'far', 'far', 'far');

-- --------------------------------------------------------

--
-- Table structure for table `user_favorites`
--

CREATE TABLE `user_favorites` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `resep_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `resep`
--
ALTER TABLE `resep`
  ADD PRIMARY KEY (`id_resep`),
  ADD UNIQUE KEY `id_resep` (`id_resep`,`judul`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`);

--
-- Indexes for table `user_favorites`
--
ALTER TABLE `user_favorites`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `user_id` (`user_id`,`resep_id`),
  ADD KEY `resep_id` (`resep_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `resep`
--
ALTER TABLE `resep`
  MODIFY `id_resep` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `user_favorites`
--
ALTER TABLE `user_favorites`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=24;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `user_favorites`
--
ALTER TABLE `user_favorites`
  ADD CONSTRAINT `user_favorites_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `user_favorites_ibfk_2` FOREIGN KEY (`resep_id`) REFERENCES `resep` (`id_resep`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
